// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus';
import { application as app } from './application'; // 名前を変更して競合を避ける
import RedirectController from './redirect_controller';
import AutocompleteController from './autocomplete_controller';

// applicationを既にインポートしているため、再定義しない
app.register('autocomplete', AutocompleteController);
app.register('redirect', RedirectController);
